# This profile gived as config for dbt_simple_bash and not required for Cosmos. 
# Do not use this file in prodution - it can be replaced with dbt env_var function (example above and docs here https://docs.getdbt.com/reference/dbt-jinja-functions/env_var) 
# or with Airflow connection with Cosmos.

jaffle_shop:
  target: dev

  outputs:
    dev:
      host: postgres
      port: 5432
      dbname: postgres
      schema: public
      user: airflow
      password: airflow
      type: postgres
      threads: 5

    # dev_with_envs:
    #   type: postgres
    #   host: "{{ env_var('DBT_ENV_SECRET_HOST') }}"
    #   port: "{{ env_var('DBT_PORT') | int }}"
    #   dbname: "{{ env_var('DBT_DATABASE') }}"
    #   schema: "{{ env_var('DBT_ENV_SECRET_SCHEMA') }}"
    #   user: "{{ env_var('DBT_ENV_SECRET_USER_NAME') }}"
    #   password: "{{ env_var('DBT_ENV_SECRET_PASSWORD') }}"
    #   threads: "{{ env_var('DBT_THREADS') | int }}"
