route:
  group_by: ['alertname', 'job']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  receiver: alerts

receivers:
- name: alerts
  slack_configs:
  - send_resolved: true
    text: "{{ .CommonAnnotations.description }}"
    channel: 'airflow_alerts'  # Your Slack channel name without the #
    api_url: 'https://hooks.slack.com/services/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'